### ISSUE TITLE
Two problems in script

### ISSUE THREAD

**Issue by cyberluke** [EOS-Jungle-Testnet/Node-Auto-installation#2]
1)
Ubuntu 18:
line 56: jq: command not found
>>
sudo apt  install jq

2)
E: Could not open lock file /var/lib/apt/lists/lock - open (13: Permission denied)
E: Unable to lock directory /var/lib/apt/lists/
W: Problem unlinking the file /var/cache/apt/pkgcache.bin - RemoveCaches (13: Permission denied)
W: Problem unlinking the file /var/cache/apt/srcpkgcache.bin - RemoveCaches (13: Permission denied)

Instructions for running script should contain 'sudo'

**Comment by bublik77** [comment]
added permission verification and notification
