### ISSUE TITLE
Auto script missing first time run

### ISSUE THREAD

**Issue by cyberluke** [EOS-Jungle-Testnet/Node-Auto-installation#3]
After running start.sh:
received a go away message from jungle2.eosdac.io:9872, reason = wrong chain

Auto script is missing this first time command: ./start.sh --delete-all-blocks --genesis-json genesis.json

**Comment by bublik77** [comment]
Hi,
you have chosen the way of sync or you have just exit?

**Comment by cyberluke** [comment]
I installed clean node using your automatic script. Upon first start.sh without genesis.json parameter, it might not know which chain to run on. After supplying the first time run, it started to work and now I can run start.sh according to docs.

**Comment by bublik77** [comment]
Added  notification to run start with the option  if you select an exit in sync select
