### ISSUE TITLE
EOS registration form - IP address

### ISSUE THREAD

**Issue by cyberluke** [EOS-Jungle-Testnet/Node-Auto-installation#4]
Website script asks for public IP address, it then puts it into config.ini.

But stderr.txt tells that it cannot bind on this address. This situation happens when running node in cloud (Amazon AWS / EC2). I want to listen on public address, but there is some routing happening, so it is not possible to do it like this. Instead the correct approach is to use 0.0.0.0 (listen on all network interfaces). 

I had to change it manually after reading stderr.txt.

I guess there should  be information to leave it at 0.0.0.0, unless some specific circumstances happen. But this also depends on percentage of users running nodes. My guess that nowadays most of users will use some cloud deployment, not private custom dedicated server.

**Comment by bublik77** [comment]
Hello,
we did not test our script on AWS, only on the bare metal server(maybe we should inform about that)
Maybe we add this possibility on the future
